name: wheels

on:
  push:
    tags:
      - '**'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest, windows-latest]

    steps:
      # Check out repository using git-lfs
      - uses: actions/checkout@v3
        with:
          lfs: true

      # Python used to run cibuildwheel
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install cibuildwheel
        run: python -m pip install --upgrade wheel setuptools pip cibuildwheel==2.11.1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # Options (https://cibuildwheel.readthedocs.io/en/stable/options/)
        env:
          CIBW_SKIP: cp36-* cp311-* *musllinux*
          CIBW_BEFORE_BUILD_MACOS: python3 -m pip install --upgrade setuptools wheel cffi
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_BUILD_FRONTEND: "build"
          # CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
